version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    volumes:
      - /home/docker-data/kafka/zookeeper/data:/data
    environment:
      KAFKA_HEAP_OPTS: "-Xms32M -Xmx32M -verbose:gc"
    ports:
      - 4030:2181

  kafka9094:
    restart: always
    image: wurstmeister/kafka
    ports:
      - 4029:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://81.70.216.18:4029
      KAFKA_CREATE_TOPICS: "first-topic:1:1"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫 first-topic 的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_HEAP_OPTS : "-Xmx256M -Xms128M"
    volumes:
      - /home/docker-data/kafka/kafka-logs:/kafka
    depends_on:
      - zookeeper